### ISSUE TITLE
Update react-center-component to 3.0.0 to stop warning when used with React 15.0

### ISSUE THREAD

**Issue by ghost** [qimingweng/react-modal-dialog#17]

**Comment by qimingweng** [comment]
@ssbiswal1987 What are you seeing...? What's the warning

**Comment by ghost** [comment]
npm WARN react-center-component@2.0.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-center-component@2.0.1 requires a peer of react-dom@^0.14.0 but none was installed.

**Comment by ghost** [comment]
https://github.com/qimingweng/react-center-component/blob/master/package.json 
react-center-component has updated it in 3.0.0

**Comment by qimingweng** [comment]
@ssbiswal1987 This is already solved, right? in #14

**Comment by ghost** [comment]
No this is not fixed. I am referring to react-center-component that you have specified as a dependency.

This is what you have in your package.json

"react-center-component": "^2.0.1",

react-center-componet 2 and above has a peer dependency on react 0.14.
In their 3.0.0 they have made it to work with react 15.0.0 and above so that no warnings is shown.

Can you update your package.json with

"react-center-component": "^3.0.0",

**Comment by qimingweng** [comment]
Ah I see what you mean, I'll update the package.json in this one then.

**Comment by ghost** [comment]
thanks

**Comment by qimingweng** [comment]
Ok fixed in 42219730cb8ce5192b328980e9de0d56cf19cbfd

**Comment by ghost** [comment]
ok
